### ISSUE TITLE
BDtubefit = BD_models[lib_list[0]] KeyError: 1

### ISSUE THREAD

**Issue by krwaring** [seb369/MetaSIPSim#1]
Hi,
I have successfully used SIPSim_metagenome.py before, but am now running into the following error:

> ...
> Your community abundance file is: community.txt
> Your incorporator assignment file is: incorporators.txt
> You are simulating with the isotope of C
> 
> It took 0.831 seconds to get these models.
> It took 0.655 seconds to get these models.
> It took 0.671 seconds to get these models.
> It took 0.646 seconds to get these models.
> 
> Building fragments
> 
> It took 625.803 seconds to build the fragments
> 
> ----------
> Traceback (most recent call last):
>  File "~/MetaSIPSim/bin/SIPSim_metagenome.py", line 445, in <module>
>    BDtubefit = BD_models[lib_list[0]]
> KeyError: 1

Can you help me figure out what's going out?

**Comment by seb369** [comment]
Can you provide a bit more information that might help me? Can you provide the contents of the configuration file that you are using?

**Comment by krwaring** [comment]
Oops, I just found my mistake- I had updated my `fractions.txt` file manually and one entry had spaces instead of tabs.
