### ISSUE TITLE
KeyError: ('a', u'occurred at index 143725')

### ISSUE THREAD

**Issue by krwaring** [seb369/MetaSIPSim#2]
Hello,
I am trying to run `nonSIP_metagenome.py` and am receiving variations of an indexing error (one example shown below) during the read sequence writing process that I can't seem to fix. The nucleotide referenced varies (I've seen, a, c, and t) and the index number varies as well when I make changes to the parameters.cfg file. My parameters.cfg file is also shown below, and I've attached the corresponding input files. Could you please let me know what you think might be going wrong?

**Error message:**
> You have chosen to get sequences of simulated, sequenced non-SIP metagenome reads.
> 
> Building fragments
> 
> It took 15.76 seconds to build the fragments
> 
> ----------
> 
> Starting library 1
> 
> Writing fragments to file
> It took 0.194 seconds to write fragment file.
> It took 7.193 seconds to generate reads. Now building map.
> Writing read sequences
> Traceback (most recent call last):
>   File "/home/krwaring/software/metasipsim/MetaSIPSim/bin/nonSIP_metagenome.py", line 477, in <module>
>     pool.map(sequence_entry, sub_df)
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/multiprocessing/pool.py", line 253, in map
>     return self.map_async(func, iterable, chunksize).get()
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/multiprocessing/pool.py", line 572, in get
>     raise self._value
> KeyError: ('a', u'occurred at index 143725')

**parameters.cfg:**
> [Library]
> library_list = 1
> window_or_fraction = fraction
> 
> [Fragment]
> genomedir = /~/metasipsim/referenceseqs
> frag_length_distribution = skewed-normal,1000,250,-5
> coverage_of_fragments = 30
> temp_fragment_file = S2_F1-tmp.frags
> genome_index_file = /~/metasipsim/inputfiles/genome_index.txt
> 
> [Gradient]
> temperature = 293.15
> avg_density = 1.69
> angular_velocity = 16860743
> min_rotation_radius = 7.47
> max_rotation_radius = 8.79
> tube_angle = 0
> tube_radius = 0.66
> tube_height = 5.1
> fraction_frag_in_dbl = 0.001
> isotope = C
> 
> [Model]
> min_bouyant_density = 1.669
> max_bouyant_density = 1.755
> bouyant_density_step = 0.0001
> fraction_table_file = /~/metasipsim/inputfiles/fractions.txt
> 
> [Community]
> community_file = /~/metasipsim/inputfiles/community.txt
> incorporator_file = /~/metasipsim/inputfiles/incorporators.txt
> 
> [Sequencing]
> max_read_length = 151
> avg_insert_size = 1000
> stddev_insert_size = 5
> final_number_of_sequences = 1342607
> number_of_sequences_per_iteration = 1342607
> 
> [Other]
> temp_directory = ./tmp
> threads = 2
> logfile = S2_F1.log
> endpoint = read_sequences

[community.txt](https://github.com/seb369/MetaSIPSim/files/5111481/community.txt)
[genome_index.txt](https://github.com/seb369/MetaSIPSim/files/5111484/genome_index.txt)
[incorporators.txt](https://github.com/seb369/MetaSIPSim/files/5111486/incorporators.txt)
[fractions.txt](https://github.com/seb369/MetaSIPSim/files/5111533/fractions.txt)

**Comment by seb369** [comment]
I will look into this more closely, but one thing that first comes to mind is having a lower case letter in your input fasta files. Can you search some of your genome files to see if there are any lower case A, C, or T in them?

**Comment by krwaring** [comment]
That was it- for some reason the reference genomes I was working with were a mix of upper and lower case letters. Thank you!
