### ISSUE TITLE
ValueError: Invalid weights: weights sum to zero

### ISSUE THREAD

**Issue by krwaring** [seb369/MetaSIPSim#3]
Hello,
Could you please provide some insight on the following error that I'm getting while running `SIPSim_metagenome.py`? It has been occurring somewhat randomly within a set of replicate libraries, all of which have identical input files. 

**Error:**

> It took 1751.717 seconds to run the library 4 fraction 1 BD:1.67-1.681
> 
> Starting library 4 fraction 2 BD:1.681-1.692
> Writing fragments to file
> It took 168.726 seconds to write fragment file.
> Traceback (most recent call last):
>   File "~/software/metasipsim/MetaSIPSim/bin/SIPSim_metagenome.py", line 576, in <module>
>     sub_df = sub_df.sample(n=number_reads, replace=True, weights='abundance', axis=0)
>   File "~/software/metasipsim/lib/python2.7/site-packages/pandas/core/generic.py", line 4845, in sample
>     raise ValueError("Invalid weights: weights sum to zero")
> ValueError: Invalid weights: weights sum to zero

**fractions.txt:**
> library	fraction	BD_min	BD_max	fraction_size
> 4	1	1.67	1.681	0.011
> 4	2	1.681	1.692	0.011
> 4	3	1.692	1.703	0.011
> 4	4	1.703	1.714	0.011
> 4	5	1.714	1.725	0.011
> 4	6	1.725	1.736	0.011
> 4	7	1.736	1.747	0.011
> 4	8	1.747	1.758	0.011
> 4	9	1.758	1.769	0.011
> 4	10	1.769	1.78	0.011
> 5	1	1.67	1.681	0.011
> 5	2	1.681	1.692	0.011
> 5	3	1.692	1.703	0.011
> 5	4	1.703	1.714	0.011
> 5	5	1.714	1.725	0.011
> 5	6	1.725	1.736	0.011
> 5	7	1.736	1.747	0.011
> 5	8	1.747	1.758	0.011
> 5	9	1.758	1.769	0.011
> 5	10	1.769	1.78	0.011
> 6	1	1.67	1.681	0.011
> 6	2	1.681	1.692	0.011
> 6	3	1.692	1.703	0.011
> 6	4	1.703	1.714	0.011
> 6	5	1.714	1.725	0.011
> 6	6	1.725	1.736	0.011
> 6	7	1.736	1.747	0.011
> 6	8	1.747	1.758	0.011
> 6	9	1.758	1.769	0.011
> 6	10	1.769	1.78	0.011

**parameters.txt:**
> [Library]
> library_list = 4, 5, 6
> window_or_fraction = fraction
> 
> [Fragment]
> genomedir = ~/00genomes/genomes
> frag_length_distribution = skewed-normal,9000,2500,-5
> coverage_of_fragments = 50
> temp_fragment_file = tmp_4-6
> genome_index_file = ~/01rawreads/metasipsim_inputfiles_4-6/community/genome_index.txt
> 
> [Gradient]
> temperature = 293.15
> avg_density = 1.70
> angular_velocity = 16860743
> min_rotation_radius = 7.47
> max_rotation_radius = 8.79
> tube_angle = 0
> tube_radius = 0.66
> tube_height = 5.1
> fraction_frag_in_dbl = 0.001
> isotope = C
> 
> [Model]
> min_bouyant_density = 1.669
> max_bouyant_density = 1.781
> bouyant_density_step = 0.0001
> fraction_table_file = ~/01rawreads/metasipsim_inputfiles_4-6/community/fractions.txt
> 
> [Community]
> community_file = ~/01rawreads/metasipsim_inputfiles_4-6/community/community.txt
> incorporator_file = ~/01rawreads/metasipsim_inputfiles_4-6/community/incorporators.txt
> 
> [Sequencing]
> max_read_length = 151
> avg_insert_size = 1000
> stddev_insert_size = 5
> final_number_of_sequences = 5000000
> number_of_sequences_per_iteration = 5000000
> 
> [Other]
> temp_directory = tmp_4-6
> threads = 2
> logfile = simulation_4-6.log
> endpoint = read_sequences

**Comment by seb369** [comment]
That is odd that it is intermittent. It looks like a problem with the weighted read sampling using the pandas sampling function. Right before this error point, there should be a tab delimited file generated with all the simulated genome fragments, something like library_4_fraction_2_fragments.txt.gz. If you take a look at that file, it should look something like the attached although much longer:
[example_fragments.txt](https://github.com/seb369/MetaSIPSim/files/6086946/example_fragments.txt)

In particular, take a look at the abundance column. If this column is all zeros, then that is the source of the error and we'll have to identify why that is occurring. Can you take a look at that file and post the top 10-20 lines?

**Comment by krwaring** [comment]
The abundances are very low but they are non-zero.
[fragments.txt](https://github.com/seb369/MetaSIPSim/files/6087197/fragments.txt)

**Comment by seb369** [comment]
Can you sum up the abundances of all fragments in that file? While doing this, can you also see if there is an 'inf' or '-inf' in that abundance column? This can cause the the error you are seeing but I'm not yet sure how that may have been generated. I'm looking into that now.

**Comment by krwaring** [comment]
The abundances sum to 297, and there is one abundance reading in the file that is "nan". It occurs for the shortest fragment length of 3 bps.

**Comment by krwaring** [comment]
The entry with "nan" as an abundance and a 3 basepair length has a GC content value of "100" in the frags_Iter1.txt file. Maybe this helps indicate something? Here are a few lines before and after the entry:

```
taxon_name	scaffoldID	fragStart	fragLength	fragGC
GCF_000328525.1_ASM32852v1	NC_019964.1 Halovivax ruber XH-70, complete sequence	2700203	7496	68.6899679829
GCF_000328525.1_ASM32852v1	NC_019964.1 Halovivax ruber XH-70, complete sequence	2707700	4742	62.9902994517
GCF_000328525.1_ASM32852v1	NC_019964.1 Halovivax ruber XH-70, complete sequence	2712443	3	100.0
GCF_000328525.1_ASM32852v1	NC_019964.1 Halovivax ruber XH-70, complete sequence	2712447	6163	63.4431283466
GCF_000328525.1_ASM32852v1	NC_019964.1 Halovivax ruber XH-70, complete sequence	2718611	8786	65.9685863874
```

**Comment by seb369** [comment]
Thats it. The NaN was causing the issue with the fragment abundance normalization, which in turn affected the weighted sampling. I'm not exactly sure why the NaN was produced but It is probably due to the 100% G+C and the extremely short fragment. I don't think those are very common so that would be why this error is intermittent. I will look why those are occurring though.

In short, I have just updated the script so that it filters out any NaN abundances, which should prevent this error from occurring again. If you pull the changes you should be good to go. Thanks for bringing this to my attention!
